### ISSUE TITLE
The Script will crash on some movies

### ISSUE THREAD

**Issue by MatejMecka** [ManveerBasra/get_netflix_activity#1]
Haven't tested it yet but a movie title like

> Breaking Bad: Season 3: "No Más"

Can Crash the script due to no UTF-8 Support!

and you may get an error like this:

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 39: ordinal not in range(128)`

**Comment by ManveerBasra** [comment]
Thanks! I didn't notice that, I'll try fixing that when I get free time

**Comment by ManveerBasra** [comment]
It doesn't crash, but it writes 'à' as '?'. I'll work on adding utf-8 support.
