### ISSUE TITLE
After scrolling down to the end of the list it doesn't end

### ISSUE THREAD

**Issue by cfsmp3** [ManveerBasra/get_netflix_activity#5]
Just tested the last version. It went to the end of my activity window (it scrolled down, down, down... that worked perfectly, so good just on that part), however it never actually finished on its own, even though the "Done" button was visible.

Once I closed Chrome myself it wrote the activity file perfectly.

So looks like a minor thing is missing.

**Comment by ManveerBasra** [comment]
I'll edit the scrolling loop to fix this

**Comment by ManveerBasra** [comment]
[Fixed Loop Scrolling Error Commit](https://github.com/ManveerBasra/get_netflix_activity/commit/26548dfff1cdd9ecfd9b57e5005a34fcc10103ed)
Hopefully it works now

**Comment by cfsmp3** [comment]
No luck :-(

**Comment by ManveerBasra** [comment]
that's weird, so it only prints `writing to netflix_activity.py` when you close chrome?

**Comment by cfsmp3** [comment]
No, actually it worked. Just takes a long time and it's totally
counterintutive... I mean I'm seeing Chrome is already at the end of the
list, then (after a few seconds) I get the message "Writing activity to
'netflix_activity.txt'" and much later Chrome is closed.

Still, this is good enough for sure, but maybe some progress info (if the
issue cannot be solved, for example because retrieving the data from Chrome
is just slow) could be added so users don't think the program is frozen?

**Comment by ManveerBasra** [comment]
The reason it happens because it scrolls down, then waits a bit before checking if the webpage has changed. If it has then it scrolls down again. It also takes time to loop through all of the table-rows and to retrieve their date and title. I'll work on speeding up the process and clarifying the activity for the user.

**Comment by ManveerBasra** [comment]
[Imroved output commit](https://github.com/ManveerBasra/get_netflix_activity/commit/a27ab4737dd7deca1d0e5f9f5547f61068438dd5)
It will now show a progress bar to the user when retrieving netflix activity.
