### ISSUE TITLE
Missing interpreter line

### ISSUE THREAD

**Issue by cfsmp3** [ManveerBasra/get_netflix_activity#6]
#!/usr/bin/python3

should be the first line of the file (also chmod +x)

**Comment by ManveerBasra** [comment]
@cfsmp3 
I added `#!/usr/bin/python3` but I don't know what do with `chmod +x`. Do I put it as a comment also? I've tried searching it up with no avail.

**Comment by cfsmp3** [comment]
If you're running linux just do the chmod +x from terminal.
If you're using windows then just forget about it :-)
